[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tower = "0.4" # Perlu untuk `ServiceExt`
tower-http = {version = "0.5", features = ["fs"]} # untuk melayani file static